fragment productNameFrag on Product {
  id
  name
  imageUrl
}
fragment productFrag on Product {
  id
  creationDate
  lastUpdate
  name
  brand
  price
  oldPrice
  imageUrl
  category  {
    ..._all_fields
  }
}





fragment productDetailsFrag on Product {
  id
  creationDate
  lastUpdate
  name
  brand
  price
  oldPrice
  imageUrl
  category @gqTypeName(name: "Category") {
    ..._all_fields
  }
  similarities @gqTypeName(name: "IndexedProduct") {
    index
    product {
      ..._all_fields
    }
  }
  complementaries {
    index
    product {
      ..._all_fields
    }
  }
}

fragment productIndexFrag on Product {
  id
  name
  score
  imageUrl
}
