fragment productNameFrag on Product {
  id
  name
  imageUrl
}
fragment productFrag on Product {
  id
  creationDate
  lastUpdate
  name
  brand
  price
  oldPrice
  imageUrl
  category @gqTypeName(name: "Category") {
    ...categoryFrag
  }
}

fragment categoryFrag on Category {
  id
  name
  creationDate
  lastUpdate
  parent {
    name
    id
    creationDate
  }
}

fragment productInfoFrag on ProductInfo {
  id
  creationDate
  lastUpdate
  name
  brand
  price
  oldPrice
  imageUrl
  category @gqTypeName(name: "Category") {
    ...categoryFrag
  }
}

fragment productDetailsFrag on Product {
  id
  creationDate
  lastUpdate
  name
  brand
  price
  oldPrice
  imageUrl
  category @gqTypeName(name: "Category") {
    ...categoryFrag
  }
  similarities @gqTypeName(name: "IndexedProduct") {
    index
    product {
      ...productInfoFrag
    }
  }
  complementaries {
    index
    product {
      ...productInfoFrag
    }
  }
}
