
fragment productFrag on Product {
  id
  creationDate
  lastUpdate
  score
  name
  brand
  designer
  category {
    ..._all_fields
  }
  shortDescription
  longDescription
  price
  oldPrice
  forKids
  gender
}


fragment productDetailsFrag on Product {
  id
  creationDate
  lastUpdate
  score
  name
  brand
  designer
  category {
    ..._all_fields
  }
  shortDescription
  longDescription
  price
  oldPrice
  forKids
  gender
  skuCount
}

fragment allFieldsProduct on Product {
  id
  creationDate
  lastUpdate
  score
  name
  brand
  designer
  category {
    ..._all_fields
  }
  shortDescription
  longDescription
  price
  oldPrice
  forKids
  gender
  skuList {
    ... _all_fields
  }
}


fragment productIndexFrag on Product {
  id
  name
  score
}
