mutation adminLogin($username: String!, $password: String!) {
  login(username: $username, password: $password)
    @gqTypeName(name: "LoginResponse") {
    token @gqTypeName(name: "ResponseToken") {
      ..._all_fields
    }
    user @gqTypeName(name: "RecsUser") {
      ..._all_fields
    }
  }
}

mutation refreshToken($token: String!) {
  data: refreshToken(token: $token) {
    token{
      ..._all_fields
    }
    user  {
      ..._all_fields
    }
  }
}

mutation updateProductSimilarities(
  $productId: String!
  $similarities: [QueueItem!]!
) {
  updateProductSimilarities(
    productId: $productId
    similarities: $similarities
  ) {
    ...productDetailsFrag
  }
}

mutation updateProductComplementaries(
  $productId: String!
  $complementaries: [QueueItem!]!
) {
  updateProductComplementaries(
    productId: $productId
    complementaries: $complementaries
  ) {
    ...productDetailsFrag
  }
}
