mutation adminLogin($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    ..._all_fields
  }
}

mutation refreshToken($token: String!) {
  refreshToken(token: $token) {
    ..._all_fields
  }
}



mutation saveCollectionMapping($input: CollectionMappingInput!) {
  saveCollectionMapping(input: $input) {
    ..._all_fields
  }
}

mutation updateDistance($id: String!, $distance: Float!) {
  updateDistance(id: $id, distance: $distance)
}
mutation updateAdjacencyDistance($id: String!, $distance: Float!) {
  updateAdjacencyDistance(id: $id, distance: $distance)
}

mutation generateIndex {
  generateIndex
}
mutation addAdjacency($input: AdjacencyInput!) {
  addAdjacency(input: $input) {
    id
  }
}
mutation deleteAdjacencyById($adjacencyId: ID!) {
  deleteAdjacencyById(adjacencyId: $adjacencyId)
}

mutation createRule($input: RuleInput!) {
  createRule(input: $input) {
    ... _all_fields
  }
}
