mutation adminLogin($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    ..._all_fields
  }
}

mutation refreshToken($token: String!) {
   refreshToken(token: $token) {
        ..._all_fields
  }
}

mutation updateProductSimilarities(
  $productId: String!
  $similarities: [QueueItem!]!
) {
  updateProductSimilarities(
    productId: $productId
    similarities: $similarities
  ) {
    ...productDetailsFrag
  }
}

mutation updateProductComplementaries(
  $productId: String!
  $complementaries: [QueueItem!]!
) {
  updateProductComplementaries(
    productId: $productId
    complementaries: $complementaries
  ) {
    ...productDetailsFrag
  }
}

mutation saveCollectionMapping($input: CollectionMappingInput!) {
   saveCollectionMapping(input: $input) {
        ..._all_fields
  }
}
