query getProducts($pageInfo: PageInfo!) {
  getProducts(pageInfo: $pageInfo) {
    ..._all_fields
  }
  total: countProducts
}
query getCategories($pageInfo: PageInfo!) {
  getCategories(pageInfo: $pageInfo) {
    ..._all_fields
  }
  total: countCategories
}

query searchProducts($pageInfo: PageInfo!, $params: ProductParamSearch!) {
  searchProducts(pageInfo: $pageInfo, params: $params) {
    ...productDetailsFrag
  }
  count: countSearchProduct(params: $params)
}

query getProductDetails($productId: String!) {
  getProductById(productId: $productId) @gqTypeName(name: "ProductDetails") {
    ...productDetailsFrag
  }
}

query getProductById($productId: String!) {
  getProductById(productId: $productId) @gqTypeName(name: "ProductWithSKU") {
    ...allFieldsProduct
  }
}

query imageSearch($skuId: String!) {
  imageSearch(skuId: $skuId) {
    ..._all_fields
  }
}
query imageSearchByText($data: String!) {
  imageSearchByText(data: $data) {
    ..._all_fields
  }
}

query collectionMappins {
  collectionMappings {
    ..._all_fields
  }
}

query getRootCategories($pageInfo: PageInfo!) {
  getRootCategories(pageInfo: $pageInfo) {
    ..._all_fields
  }
  total: countRootCategories
}
query findCategoriesByParentId($parentId: String!, $pageInfo: PageInfo!) {
  findCategoriesByParentId(parentId: $parentId, pageInfo: $pageInfo) {
    ..._all_fields
  }
  total: countCategoriesByParentId(parentId: $parentId)
}
query getCategoryTree {
  getCategoryTree {
    ..._all_fields
  }
}
query listIndexElements($pageInfo: PageInfo!, $name: String) {
  listIndexElements(pageInfo: $pageInfo, name: $name) {
    ..._all_fields
  }
  total: countIndexElements(name: $name)
}
query getColorIndexByColorHex($color: String!, $pageInfo: PageInfo!) {
  findColorIndexByColorHex(color: $color, pageInfo: $pageInfo) {
    ..._all_fields
  }
}
query getAdjecencyEntries($type: AdjacencyType!) {
  getAdjecencyEntries(type: $type)
}
query getAdjacencies($pageInfo: PageInfo!, $type: AdjacencyType!) {
  getAdjacencies(pageInfo: $pageInfo, type: $type) {
    ..._all_fields
  }
  total: countAdjacenciesByType(type: $type)
}
