query getProducts($pageInfo: PageInfo!) {
  getProducts(pageInfo: $pageInfo) {
    ..._all_fields
  }
  total: countProducts
}
query getCategories($pageInfo: PageInfo!) {
  getCategories(pageInfo: $pageInfo) {
    ..._all_fields
  }
  total: countCategories
}

query searchProducts($pageInfo: PageInfo!, $params: ProductParamSearch!){
  searchProducts(pageInfo: $pageInfo, params: $params)  {
    ...productDetailsFrag
  }
  count: countSearchProduct(params: $params)
}

query getProductDetails($productId: String!) {
  getProductById(productId: $productId) @gqTypeName(name: "ProductDetails") {
    ...productDetailsFrag
  }
}

query getProductById($productId: String!) {
  getProductById(productId: $productId)@gqTypeName(name: "ProductWithSKU")  {
    ...allFieldsProduct
  }
}

query imageSearch($productId: String!) {
  imageSearch(productId: $productId) {
    ..._all_fields
  }
}
query imageSearchByText($data: String!) {
  imageSearchByText(data: $data)  {
    ..._all_fields
  }
}


query collectionMappins() {
  collectionMappings {
    ..._all_fields
  }
}