query getProducts($pageInfo: PageInfo!) {
  getProducts(pageInfo: $pageInfo) @gqTypeName(name: "Product") {
    ...productFrag
  }
  total: countProducts
}
query getCategories($pageInfo: PageInfo!) {
  getCategories(pageInfo: $pageInfo) @gqTypeName(name: "Category") {
    ...categoryFrag
  }
  total: countCategories
}

query searchProducts($pageInfo: PageInfo!, $params: ProductParamSearch!) {
  searchProducts(pageInfo: $pageInfo, params: $params) {
    ...productFrag
  }
  count: countSearchProduct(params: $params)
}

query getProductDetails($productId: String!) {
  getProductById(productId: $productId) @gqTypeName(name: "ProductDetails") {
    ...productDetailsFrag
  }
}
query getProductName($productId: String!) {
  getProductById(productId: $productId) @gqTypeName(name: "ProductName") {
    ...productNameFrag
  }
}
