#*************************** SCALAR ***************************
scalar Long
#*************************** INTERFACE ***************************
interface BasicEntity {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
}
################################# QUERIES #############################

type Query {
  sayHello: String!
  getProductById(productId: String!): Product!
  getProducts(pageInfo: PageInfo!): [Product!]!
  getCategoryById(categoryId: String!): Category!
  getCategories(pageInfo: PageInfo!): [Category!]!
  countProducts: Long!
  countCategories: Long!
  searchProducts(pageInfo: PageInfo!, params: ProductParamSearch!): [Product!]!
  countSearchProduct(params: ProductParamSearch!): Long!
  imageSearch(productId: String!): [Product!]!
  imageSearchByText(data: String!): [Product!]!
  collectionMappings: [CollectionMapping!]!
}
################################# MUTATIONS #############################

type Mutation {
  login(username: String!, password: String!): TokenUser!
  refreshToken(token: String!): TokenUser!
  addUser(name: String!): User!
  deleteProductById(productId: String!): ID
  deleteCategoryById(categoryId: String!): ID
  addCategory(input: CategoryInput!): Category!
  updateProductSimilarities(
    productId: String!
    similarities: [QueueItem!]!
  ): Product!

  updateProductComplementaries(
    productId: String!
    complementaries: [QueueItem!]!
  ): Product!

  saveCollectionMapping(input: CollectionMappingInput!): CollectionMapping!
}
################################# TYPES #############################

type User implements BasicEntity {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
  name: String!
}

type ResponseToken {
  accessToken: String!
  expiresIn: Int!
  refreshExpiresIn: Int!
  refreshToken: String!
  tokenType: String!
  notBeforePolicy: Int!
  sessionState: String!
  scope: String!
}

type TokenUser {
  token: ResponseToken!
  user: FeUser!
}

type FeUser {
  name: String!
  email: String
  roles: [String!]!
}

type RecsUser {
  exp: Long!
  iat: Long!
  jti: String!
  iss: String!
  aud: String!
  sub: String!
  typ: String!
  azp: String!
  sessionState: String!
  acr: String!
  allowedOrigins: [String!]!
  realmAccess: RealmAccess!
  resourceAccess: ResourceAccess!
  scope: String!
  sid: String!
  emailVerified: Boolean!
  name: String
  preferredUsername: String!
  givenName: String
  familyName: String
  email: String
}

type RealmAccess {
  roles: [String!]!
}

type ResourceAccess {
  account: Account!
}

type Account {
  roles: [String!]!
}

type Product implements BasicEntity {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
  name: String!
  brand: String!
  price: Float!
  oldPrice: Float!
  imageUrl: String
  category: Category!
  similarities: [IndexedProduct!]!
  complementaries: [IndexedProduct!]!
  score: Float!
}

type IndexedProduct {
  index: Int!
  product: ProductInfo!
}

type ProductInfo {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
  name: String!
  brand: String!
  price: Float!
  oldPrice: Float!
  imageUrl: String
  category: Category!
}

type Category implements BasicEntity {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
  name: String!
  parent: CategoryInfo
}
type CategoryInfo {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
  name: String!
}

type CollectionMapping {
  id: ID
  creationDate: Long!
  lastUpdate: Long!
  headers: [String!]!
  dateFormat: String
  fileMask: String
  delimiter: String
  collectionName: String!
  collectionLabel: String!
  fields: [FieldMapping!]!
}

type FieldMapping {
  label: String!
  name: String!
  type: DataType!
  required: Boolean!
  csvFieldValue: String
  csvFieldDefaultValue: String
}
################################# INPUTS #############################

input CollectionMappingInput {
  id: String
  headers: [String]!
  dateFormat: String!
  fileMask: String!
  delimiter: String!
  collectionName: String!
  collectionLabel: String!
  fields: [FieldMappingInput!]!
}

input FieldMappingInput {
  label: String!
  name: String!
  type: DataType!
  csvFieldValue: String
  required: Boolean
  csvFieldDefaultValue: String
}

input ProductInput {
  name: String!
  brand: String!
  price: Float!
  oldPrice: Float!
  imageUrl: String
  categoryId: String!
}

input PageInfo {
  page: Int!
  size: Int!
}
input CategoryInput {
  name: String!
  parentId: String
}

input ProductParamSearch {
  productId: String
  name: String
  brand: String
  categoryIds: [String!]
}

input QueueItem {
  productId: String!
  rank: Int!
}
################################# ENUMS #############################
enum DataType {
  STRING
  DOUBLE
  INT
  BOOLEAN
  DATE
  DATETIME
}