#*************************** SCALAR ***************************
scalar Long
#*************************** INTERFACE ***************************
interface BasicEntity {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
}
################################# QUERIES #############################

type Query {
  sayHello: String!
  getProductById(productId: String!): Product!
  getProducts(pageInfo: PageInfo!): [Product!]!
  getCategoryById(categoryId: String!): Category!
  getCategories(pageInfo: PageInfo!): [Category!]!
  countProducts: Long!
  countCategories: Long!
}
################################# MUTATIONS #############################

type Mutation {
  login(username: String!, password: String!): TokenUser!
  refreshToken(token: String!): TokenUser!
  addUser(name: String!): User!
  deleteProductById(productId: String!): ID
  addProduct(input: ProductInput!): Product!
  deleteCategoryById(categoryId: String!): ID
  addCategory(input: CategoryInput!): Category!
}
################################# TYPES #############################

type User implements BasicEntity {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
  name: String!
}

type ResponseToken {
  accessToken: String!
  expiresIn: Int!
  refreshExpiresIn: Int!
  refreshToken: String!
  tokenType: String!
  notBeforePolicy: Int!
  sessionState: String!
  scope: String!
}

type TokenUser {
  token: ResponseToken!
  user: RecsUser!
}

type RecsUser {
  exp: Long!
  iat: Long!
  jti: String!
  iss: String!
  aud: String!
  sub: String!
  typ: String!
  azp: String!
  sessionState: String!
  acr: String!
  allowedOrigins: [String!]!
  realmAccess: RealmAccess!
  resourceAccess: ResourceAccess!
  scope: String!
  sid: String!
  emailVerified: Boolean!
  name: String
  preferredUsername: String!
  givenName: String
  familyName: String
  email: String
}

type RealmAccess {
  roles: [String!]!
}

type ResourceAccess {
  account: Account!
}

type Account {
  roles: [String!]!
}

type Product implements BasicEntity {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
  name: String!
  brand: String!
  price: Float!
  oldPrice: Float!
  imageUrl: String
  category: Category!
}
type Category implements BasicEntity {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
  name: String!
  parent: CategoryInfo
}
type CategoryInfo {
  id: ID!
  creationDate: Long!
  lastUpdate: Long!
  name: String!
}
################################# INPUTS #############################
input ProductInput {
  name: String!
  brand: String!
  price: Float!
  oldPrice: Float!
  imageUrl: String
  categoryId: String!
}

input PageInfo {
  page: Int!
  size: Int!
}
input CategoryInput {
  name: String!
  parentId: String
}
################################# ENUMS #############################
